[package]
name = "nice-rust"
version = "1.1.4"
authors = ["wasabipesto <nice@wasabipesto.com>"]
description = "a client for distributed search of square-cube pandigitals"
repository = "https://github.com/wasabipesto/nice-rust"
license-file = "LICENSE.txt"

[dependencies]
clap = { version = "4.1" }
num-bigint = { version = "0.4" }
openssl = { version = "*", features = ["vendored"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }