name: Rust Cross-Platform Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  OUTPUT_PREFIX: nice
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    name: ${{ matrix.platform.build_name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:

          - build_name: Linux-x86_64-gnu
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu

          - build_name: Linux-x86_64-musl
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl

          - build_name: Linux-aarch64-gnu
            os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu

          - build_name: Linux-aarch64-musl
            os: ubuntu-20.04
            target: aarch64-unknown-linux-musl

          - build_name: Linux-armv7-gnu
            os: ubuntu-20.04
            target: armv7-unknown-linux-gnueabihf

          - build_name: Linux-arm-musl
            os: ubuntu-20.04
            target: arm-unknown-linux-musleabi

          - build_name: Linux-riscv64gc-gnu
            os: ubuntu-20.04
            target: riscv64gc-unknown-linux-gnu

          - build_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - build_name: Darwin-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4
      
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      
      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.platform.target, 'musl')
      
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: stable
          args: "--locked --release"
          strip: true
      
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "test"
          target: ${{ matrix.platform.target }}
          toolchain: stable
          args: "--locked --release"
        if: ${{ !matrix.platform.skip_tests }}

      - name: Get version for filename
        id: cargo_get_version
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: package.version
      
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ env.OUTPUT_PREFIX }}-${{ steps.cargo_get_version.outputs[0] }}-${{ matrix.platform.build_name }}-${{ github.sha }}.zip ${{ steps.cargo_output.outputs.cargo_name }}.exe
          else
            tar czvf ../../../${{ env.OUTPUT_PREFIX }}-${{ steps.cargo_get_version.outputs[0] }}-${{ matrix.platform.build_name }}-${{ github.sha }}.tar.gz ${{ steps.cargo_output.outputs.cargo_name }}
          fi
          cd -
      
      - name: Publish release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.OUTPUT_PREFIX }}-${{ steps.cargo_get_version.outputs[0] }}-${{ matrix.platform.build_name }}-${{ github.sha }}
          path: "${{ env.OUTPUT_PREFIX }}-*"
